apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-test1
  namespace: helm-test1
spec:
  serviceAccountName: helm-test1
  chart:
    spec:
      chart: ./mychart1
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: helm-test1-1
        namespace: helm-test1
  interval: 1m
